name: Deployment pipeline

on:
  push:
    branches:
      - master
  pull_request:    
    branches: [master]    
    types: [opened, synchronize]

jobs: 
  deployment_pipeline:
    runs-on: ubuntu-20.04
      steps:
        -name: Test
          run: echo "hello"