name: Hello World!

on:
  push:
    branches:
      - master
      # note that your "main" branch might be called main instead of master

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-20.04
    env:
      MONGODB_URI: ${{ secrets.MONGODB_URI }}
      TEST_MONGODB_URI: ${{ secrets.TEST_MONGODB_URI }}
      PORT: ${{ secrets.PORT }}
      SECRET: ${{ secrets.SECRET }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Install dependencies backend
        working-directory: ./
        run: npm install
      - name: Check style backend
        working-directory: ./       
        run: npm run eslint
      - name: Test backend
        run: npm run test
      - name: Install dependencies frontend
        working-directory: ./bloglist-frontend
        run: npm install
      - name: Check style frontend
        working-directory: ./bloglist-frontend       
        run: npm run eslint
      - name: Build frontend
        working-directory: ./bloglist-frontend
        run: npm run build
      - name: Start server and frontend
        run: npm start:test
      - name: e2e test with Cypress
        uses: cypress-io/github-action@v5
        with:
          command: npm run test:e2e
          start: npm run start:test
          wait-on: "http://localhost:3000"
      
          
