name: Hello World!

on:
  push:
    branches:
      - master
      # note that your "main" branch might be called main instead of master

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 'latest'
      - name: Install dependencies backend
        working-directory: ./
        run: npm install
      - name: Check style backend
        working-directory: ./       
        run: npm run eslint
      - name: Start backend test
        env:
          TEST_MONGODB_URI: ${{ secrets.MONGODB_URI }}
        run: npm run start:test
      - name: Test backend
        run: npm run test

      - name: Install dependencies frontend
        working-directory: ./bloglist-frontend
        run: npm install
      - name: Check style frontend
        working-directory: ./bloglist-frontend       
        run: npm run eslint
      - name: Build frontend
        working-directory: ./bloglist-frontend
        run: npm run build
          
          